INSERT INTO Address(id_address,Place) VALUES (1,'Kotto Entre Camtel');
INSERT INTO Address(id_address,Place) VALUES (2,'Carrefour Yoro Joss');
INSERT INTO Address(id_address,Place) VALUES (3,'Hotel la Falaise Bonapriso');
INSERT INTO Address(id_address,Place) VALUES (4,'Hotel la Falaise Bonadjo');
INSERT INTO Address(id_address,Place) VALUES (5,'Hotel la Falaise Akwa');
INSERT INTO Address(id_address,Place) VALUES (6,'Hotel Akwa Palace');
INSERT INTO Address(id_address,Place) VALUES (7,'Bonamoussadi IPPB');
INSERT INTO Address(id_address,Place) VALUES (8,'Bonamoussadi Carrefour Lycee');
INSERT INTO Address(id_address,Place) VALUES (9,'Bonamoussadi JC');
INSERT INTO Address(id_address,Place) VALUES (10,'B');
INSERT INTO Address(id_address,Place) VALUES (11,'B');
INSERT INTO Address(id_address,Place) VALUES (12,'B');
INSERT INTO Address(id_address,Place) VALUES (13,'B');
INSERT INTO Address(id_address,Place) VALUES (14,'B');
INSERT INTO Address(id_address,Place) VALUES (15,'B');
INSERT INTO Address(id_address,Place) VALUES (16,'B');
INSERT INTO Address(id_address,Place) VALUES (17,'B');
INSERT INTO Address(id_address,Place) VALUES (18,'B');
INSERT INTO Address(id_address,Place) VALUES (19,'B');
INSERT INTO Address(id_address,Place) VALUES (20,'B');
INSERT INTO Address(id_address,Place) VALUES (21,'B');
INSERT INTO Address(id_address,Place) VALUES (22,'B');
INSERT INTO Address(id_address,Place) VALUES (23,'B');
INSERT INTO Address(id_address,Place) VALUES (24,'B');
INSERT INTO Address(id_address,Place) VALUES (25,'B');
INSERT INTO Address(id_address,Place) VALUES (26,'B');
INSERT INTO Address(id_address,Place) VALUES (27,'B');
INSERT INTO Address(id_address,Place) VALUES (28,'B');
INSERT INTO Address(id_address,Place) VALUES (29,'B');
INSERT INTO Address(id_address,Place) VALUES (30,'B');
INSERT INTO Address(id_address,Place) VALUES (31,'B');
INSERT INTO Address(id_address,Place) VALUES (32,'B');
INSERT INTO Address(id_address,Place) VALUES (33,'B');
INSERT INTO Address(id_address,Place) VALUES (34,'B');
INSERT INTO Address(id_address,Place) VALUES (35,'B');
INSERT INTO Address(id_address,Place) VALUES (36,'B');
INSERT INTO Address(id_address,Place) VALUES (37,'B');
INSERT INTO Address(id_address,Place) VALUES (38,'B');
INSERT INTO Address(id_address,Place) VALUES (39,'B');
INSERT INTO Address(id_address,Place) VALUES (40,'B');