Prompt ******  Populating  Restaurant ....
INSERT INTO Restaurant(id_resto,username_resto,password,Name_resto,Description,Name_employees,Date_res_created,latitude,longitude,id_order,id_role)VALUES(0001,'Friends','ispania','Friends Food','Fast-food','Gilbert',TO_DATE('11/10/2021', 'DD/MM/YYYY'),'4 03 Nord','9 42 Est',0001,1);
INSERT INTO Restaurant(id_resto,username_resto,password,Name_resto,Description,Name_employees,Date_res_created,latitude,longitude,id_order,id_role)VALUES(0002,'fourchettt','cinqfour','5 Fourchettes','Un peu de tout','Albert',TO_DATE('21/04/2022', 'DD/MM/YYYY'),'4 03 Nord','9 42 Est',0002,1);
INSERT INTO Restaurant(id_resto,username_resto,password,Name_resto,Description,Name_employees,Date_res_created,latitude,longitude,id_order,id_role)VALUES(0003,'lynx','chataugrosyeux','Lynk','bar-restaurant','Bernard',TO_DATE('14/09/2022', 'DD/MM/YYYY'),'4 03 Nord','9 42 Est',,0003,1);
INSERT INTO Restaurant(id_resto,username_resto,password,Name_resto,Description,Name_employees,Date_res_created,latitude,longitude,id_order,id_role)VALUES(0004,'pizayollo','piz@','LA PIZZERIA','PIZZA','Alfredo',TO_DATE('23/10/2021', 'DD/MM/YYYY'),'4 03 Nord','9 42 Est',0004,1);
INSERT INTO Restaurant(id_resto,username_resto,password,Name_resto,Description,Name_employees,Date_res_created,latitude,longitude,id_order,id_role)VALUES(0005,'Africain','Afrique.com','Saga Africa','Mets Africain','Jason',TO_DATE('02/08/2021', 'DD/MM/YYYY'),'4 03 Nord','9 42 Est',0005,1);
INSERT INTO Restaurant(id_resto,username_resto,password,Name_resto,Description,Name_employees,Date_res_created,latitude,longitude,id_order,id_role)VALUES(0006,'venezia','piccolo#$','L Italien-Piccola Venezia','Restau Italien','Crispin',TO_DATE('26/10/2021', 'DD/MM/YYYY'),'4 03 Nord','9 42 Est',0006,1);
INSERT INTO Restaurant(id_resto,username_resto,password,Name_resto,Description,Name_employees,Date_res_created,latitude,longitude,id_order,id_role)VALUES(0007,'tradition','azerty@','Traditional-food','Mets Africain','Stephanie',TO_DATE('08/02/2021', 'DD/MM/YYYY'),'4 03 Nord','9 42 Est',0007,1);
INSERT INTO Restaurant(id_resto,username_resto,password,Name_resto,Description,Name_employees,Date_res_created,latitude,longitude,id_order,id_role)VALUES(0008,'philosophe','science&@','Le Socrate','Un peu de tout','Yvan',TO_DATE('09/02/2021', 'DD/MM/YYYY'),'3 50 29.04 Nord', '11 29 31.56 Est',0008,1);
INSERT INTO Restaurant(id_resto,username_resto,password,Name_resto,Description,Name_employees,Date_res_created,latitude,longitude,id_order,id_role)VALUES(0009,'c_pizza','pizza!@','C-PIZZA','PIZZA','Nathan',TO_DATE('15/07/2021', 'DD/MM/YYYY'),'3 50 29.04 Nord', '11 29 31.56 Est',0009,1);
INSERT INTO Restaurant(id_resto,username_resto,password,Name_resto,Description,Name_employees,Date_res_created,latitude,longitude,id_order,id_role)VALUES(0010,'monchoix','choix1@','K MyChoice','Fast-food','Maxime',TO_DATE('21/09/2020', 'DD/MM/YYYY'),'3 50 29.04 Nord', '11 29 31.56 Est',0010,1);
INSERT INTO Restaurant(id_resto,username_resto,password,Name_resto,Description,Name_employees,Date_res_created,latitude,longitude,id_order,id_role)VALUES(0011,'tchop','yamo#','Tchop et Yamo','Fast-food','Calvine',TO_DATE('11/05/2020', 'DD/MM/YYYY'),'3 50 29.04 Nord', '11 29 31.56 Est',0011,1);
INSERT INTO Restaurant(id_resto,username_resto,password,Name_resto,Description,Name_employees,Date_res_created,latitude,longitude,id_order,id_role)VALUES(0012,'HiltonValle','hit2.0@','Hilton','Restaurants-chics','Manuel',TO_DATE('29/06/2021', 'DD/MM/YYYY'),'3 50 29.04 Nord', '11 29 31.56 Est',0012,1);
INSERT INTO Restaurant(id_resto,username_resto,password,Name_resto,Description,Name_employees,Date_res_created,latitude,longitude,id_order,id_role)VALUES(0013,'SimCity','Sim@#','Restaurant SIM','Mets Traditionnel','Stephane',TO_DATE('28/02/2021', 'DD/MM/YYYY'),'5 28 nord','10 25 est',0013,1);
INSERT INTO Restaurant(id_resto,username_resto,password,Name_resto,Description,Name_employees,Date_res_created,latitude,longitude,id_order,id_role)VALUES(0014,'pizzeria','pizeria@ 2.0','Le plaisir du Gout Pizzeria','PIZZA','Kabhy',TO_DATE('01/03/2021', 'DD/MM/YYYY'),'2 56 14.1 Nord','9 54 27.5 Est',0014,1);
INSERT INTO Restaurant(id_resto,username_resto,password,Name_resto,Description,Name_employees,Date_res_created,latitude,longitude,id_order,id_role)VALUES(0015,'African','Afrique!$','Ebene plus','Mets Africain','Nono',TO_DATE('10/11/2021', 'DD/MM/YYYY'),'2 56 14.1 Nord','9 54 27.5 Est',0015,1);
INSERT INTO Restaurant(id_resto,username_resto,password,Name_resto,Description,Name_employees,Date_res_created,latitude,longitude,id_order,id_role)VALUES(0016,'Marine','Mer','Pieds dans l eau','aliment marin','Estebane',TO_DATE('15/11/2021', 'DD/MM/YYYY'),'2 56 14.1 Nord','9 54 27.5 Est',0016,1);
,'',''