INSERT INTO Payment (id_payment,payment_method) VALUES(1,'Payement en espece');
INSERT INTO Payment (id_payment,payment_method) VALUES(2,'Mtn MOMO');
INSERT INTO Payment (id_payment,payment_method) VALUES(3,'Orange Money');
INSERT INTO Payment (id_payment,payment_method) VALUES(4,'VISA');
INSERT INTO Payment (id_payment,payment_method) VALUES(5,'Wallet');
INSERT INTO Payment (id_payment,payment_method) VALUES(6,'VISA');
INSERT INTO Payment (id_payment,payment_method) VALUES(7,'Orange Money');
INSERT INTO Payment (id_payment,payment_method) VALUES(8,'Wallet');
INSERT INTO Payment (id_payment,payment_method) VALUES(9,'Mtn MOMO');
INSERT INTO Payment (id_payment,payment_method) VALUES(10,'Payement en espece');
INSERT INTO Payment (id_payment,payment_method) VALUES(11,'VISA');
INSERT INTO Payment (id_payment,payment_method) VALUES(12,'Orange Money');
INSERT INTO Payment (id_payment,payment_method) VALUES(13,'Wallet');
INSERT INTO Payment (id_payment,payment_method) VALUES(14,'Mtn MOMO');
INSERT INTO Payment (id_payment,payment_method) VALUES(15,'Payement en espece');
INSERT INTO Payment (id_payment,payment_method) VALUES(16,'VISA');
INSERT INTO Payment (id_payment,payment_method) VALUES(17,'Orange Money');
INSERT INTO Payment (id_payment,payment_method) VALUES(18,'Wallet');
INSERT INTO Payment (id_payment,payment_method) VALUES(19,'Mtn MOMO');
INSERT INTO Payment (id_payment,payment_method) VALUES(20,'Payement en espece');
INSERT INTO Payment (id_payment,payment_method) VALUES(21,'VISA');
INSERT INTO Payment (id_payment,payment_method) VALUES(22,'Orange Money');
INSERT INTO Payment (id_payment,payment_method) VALUES(23,'Wallet');
INSERT INTO Payment (id_payment,payment_method) VALUES(24,'Mtn MOMO');
INSERT INTO Payment (id_payment,payment_method) VALUES(25,'Payement en espece');
INSERT INTO Payment (id_payment,payment_method) VALUES(26,'VISA');
INSERT INTO Payment (id_payment,payment_method) VALUES(27,'Orange Money');
INSERT INTO Payment (id_payment,payment_method) VALUES(28,'Wallet');
INSERT INTO Payment (id_payment,payment_method) VALUES(29,'Mtn MOMO');
INSERT INTO Payment (id_payment,payment_method) VALUES(30,'Payement en espece');
INSERT INTO Payment (id_payment,payment_method) VALUES(31,'VISA');
INSERT INTO Payment (id_payment,payment_method) VALUES(32,'Orange Money');
INSERT INTO Payment (id_payment,payment_method) VALUES(33,'Wallet');
INSERT INTO Payment (id_payment,payment_method) VALUES(34,'Mtn MOMO');
INSERT INTO Payment (id_payment,payment_method) VALUES(35,'Payement en espece');
INSERT INTO Payment (id_payment,payment_method) VALUES(36,'VISA');
INSERT INTO Payment (id_payment,payment_method) VALUES(37,'Orange Money');
INSERT INTO Payment (id_payment,payment_method) VALUES(38,'Wallet');
INSERT INTO Payment (id_payment,payment_method) VALUES(39,'Mtn MOMO');
INSERT INTO Payment (id_payment,payment_method) VALUES(40,'Payement en espece');


--*********BY KANGUE*********--