INSERT INTO Address(id_address,Place) VALUES (1,'Kotto Entre Camtel');
INSERT INTO Address(id_address,Place) VALUES (2,'Carrefour Yoro Joss');
INSERT INTO Address(id_address,Place) VALUES (3,'Hotel la Falaise Bonapriso');
INSERT INTO Address(id_address,Place) VALUES (4,'Hotel la Falaise Bonandjo');
INSERT INTO Address(id_address,Place) VALUES (5,'Bepanda Tonnere');
INSERT INTO Address(id_address,Place) VALUES (6,'Hotel Akwa Palace');
INSERT INTO Address(id_address,Place) VALUES (7,'Bonamoussadi IPPB');
INSERT INTO Address(id_address,Place) VALUES (8,'Bonamoussadi Carrefour Lycee');
INSERT INTO Address(id_address,Place) VALUES (9,'Bonamoussadi JC');
INSERT INTO Address(id_address,Place) VALUES (10,'Bonaberi Dikolo');
INSERT INTO Address(id_address,Place) VALUES (11,'Kotto Carrefour des Immeubles');
INSERT INTO Address(id_address,Place) VALUES (12,'New Bell cimetier');
INSERT INTO Address(id_address,Place) VALUES (13,'Logbessou IUC');
INSERT INTO Address(id_address,Place) VALUES (14,'Bonaberi Enjeje Belle');
INSERT INTO Address(id_address,Place) VALUES (15,'Bali Super U');
INSERT INTO Address(id_address,Place) VALUES (16,'Montée Saint Michel');
INSERT INTO Address(id_address,Place) VALUES (17,'Bonamoussadi IPPB');
INSERT INTO Address(id_address,Place) VALUES (18,'Bonamoussadi Bijou');
INSERT INTO Address(id_address,Place) VALUES (19,'Sodiko');
INSERT INTO Address(id_address,Place) VALUES (20,'Makepe Orchidee');
INSERT INTO Address(id_address,Place) VALUES (21,'Bonamoussadi Terminus');
INSERT INTO Address(id_address,Place) VALUES (22,'Akwa Saint Jerome');
INSERT INTO Address(id_address,Place) VALUES (23,'PK13 Sweet Life');
INSERT INTO Address(id_address,Place) VALUES (24,'PK14');
INSERT INTO Address(id_address,Place) VALUES (25,'Hotel la Falaise Akwa');
INSERT INTO Address(id_address,Place) VALUES (26,'Bao Saint Michel');
INSERT INTO Address(id_address,Place) VALUES (27,'Makepe Missoke');
INSERT INTO Address(id_address,Place) VALUES (28,'Bonamoussadi Laureat');
INSERT INTO Address(id_address,Place) VALUES (29,'Bonamoussadi JC');
INSERT INTO Address(id_address,Place) VALUES (30,'Bonaberi Grand Hangar');
INSERT INTO Address(id_address,Place) VALUES (31,'Akwa College Libermann');
INSERT INTO Address(id_address,Place) VALUES (32,'Carrefour Yoro Joss');
INSERT INTO Address(id_address,Place) VALUES (33,'Makepe Rhone Poulin');
INSERT INTO Address(id_address,Place) VALUES (34,'Bonaberi Les Paletuviers');
INSERT INTO Address(id_address,Place) VALUES (35,'Kotto Happy Sport');
INSERT INTO Address(id_address,Place) VALUES (36,'Logbessou IUC');
INSERT INTO Address(id_address,Place) VALUES (37,'Bonamoussadi Mosquée');
INSERT INTO Address(id_address,Place) VALUES (38,'Deido College Alfred Saker');
INSERT INTO Address(id_address,Place) VALUES (39,'Deido Grand Moulin');


--*********BY KANGUE*********--