SET FEEDBACK 1
SET NUMWIDTH 10
SET LINESIZE 3000
SET TRIMSPOOL ON
SET TAB OFF
SET PAGESIZE 100
SET ECHO OFF

CREATE TABLE Address 
(
  id_address INT      NOT NULL,
  Place VARCHAR2(50) NOT NULL
);
 --******BY KANGUE*******--