SET FEEDBACK 1
SET NUMWIDTH 10
SET LINESIZE 3000
SET TRIMSPOOL ON
SET TAB OFF
SET PAGESIZE 100
SET ECHO OFF

CREATE TABLE Category
(
    id_category INT        NOT NULL,
    Name_cat VARCHAR(20) NOT NULL
);
/* Cree par annaellejosee13*/

