SET FEEDBACK 1
SET NUMWIDTH 10
SET LINESIZE 3000
SET TRIMSPOOL ON
SET TAB OFF
SET PAGESIZE 100
SET ECHO OFF

CREATE TABLE Roles
(
    id_role  INT          NOT NULL,
    role     VARCHAR2(5) NOT NULL
);
/* Cree par Samy Bodio */