SET FEEDBACK 1
SET NUMWIDTH 10
SET LINESIZE 3000
SET TRIMSPOOL ON
SET TAB OFF
SET PAGESIZE 100
SET ECHO OFF

CREATE TABLE Payment 
(
  id_payment     INT          NOT NULL,
  payment_method VARCHAR2(25) NOT NULL
);

 --******BY KANGUE*******--